package fetcher

import (
	"cmp"
	"context"
	"errors"
	"net/url"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"testing"
	"time"

	"github.com/samsar/curio/internal/urlutil"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestExtractVideoID(t *testing.T) {
	cases := []struct {
		name string
		url  string
		want string
		ok   bool
	}{
		{"standard", "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"no www", "https://youtube.com/watch?v=dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"mobile", "https://m.youtube.com/watch?v=dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"short link", "https://youtu.be/dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"shorts", "https://www.youtube.com/shorts/dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"live", "https://www.youtube.com/live/dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"embed", "https://www.youtube.com/embed/dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"with tracking", "https://www.youtube.com/watch?v=dQw4w9WgXcQ&si=abc&list=PL123", "dQw4w9WgXcQ", true},
		{"playlist only", "https://www.youtube.com/playlist?list=PL123", "", false},
		{"channel page", "https://www.youtube.com/@channel", "", false},
		{"homepage", "https://www.youtube.com/", "", false},
		{"not youtube", "https://example.com/watch?v=dQw4w9WgXcQ", "", false},
		{"youtu.be bare", "https://youtu.be/", "", false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			u, err := url.Parse(tc.url)
			require.NoError(t, err)
			got, ok := urlutil.YouTubeVideoID(u)
			assert.Equal(t, tc.ok, ok)
			if ok {
				assert.Equal(t, tc.want, got)
			}
		})
	}
}

func TestParseVTT_Manual(t *testing.T) {
	vtt := `WEBVTT
Kind: captions
Language: en

00:00:01.000 --> 00:00:04.000
Welcome to this talk about databases.

00:00:04.500 --> 00:00:08.000
Today we'll cover indexing strategies.

00:00:08.500 --> 00:00:12.000
First, let's look at B-trees.

00:00:12.500 --> 00:00:16.000
B-trees are balanced tree structures.

00:00:16.500 --> 00:00:20.000
They provide O(log n) lookups.
`
	got := parseVTT([]byte(vtt))
	assert.Contains(t, got, "Welcome to this talk about databases.")
	assert.Contains(t, got, "B-trees are balanced tree structures.")
	assert.NotContains(t, got, "00:00")
	assert.NotContains(t, got, "WEBVTT")
}

func TestParseVTT_AutoGenerated(t *testing.T) {
	// Auto-generated VTT has <c> tags and rolling duplicate lines.
	vtt := `WEBVTT
Kind: captions
Language: en

00:00:00.000 --> 00:00:02.400 align:start position:0%
welcome<00:00:00.480><c> to</c><c> this</c><c> talk</c>

00:00:02.400 --> 00:00:04.800 align:start position:0%
welcome to this talk
about<00:00:02.880><c> databases</c>

00:00:04.800 --> 00:00:07.200 align:start position:0%
about databases
today<00:00:05.280><c> we</c><c> will</c><c> cover</c>
`
	got := parseVTT([]byte(vtt))
	assert.Contains(t, got, "welcome to this talk")
	assert.Contains(t, got, "about databases")
	assert.Contains(t, got, "today we will cover")
	// Should not contain duplicate "about databases" or HTML tags
	assert.NotContains(t, got, "<c>")
	assert.NotContains(t, got, "<00:00")
	assert.Equal(t, 1, countOccurrences(got, "about databases"))
}

func TestParseVTT_Empty(t *testing.T) {
	assert.Equal(t, "", parseVTT([]byte("WEBVTT\n\n")))
	assert.Equal(t, "", parseVTT([]byte("")))
}

func TestFormatYouTubeMarkdown(t *testing.T) {
	meta := &ytdlpMeta{
		Title:       "Database Internals Talk",
		Channel:     "Tech Conference",
		UploadDate:  "20240315",
		Duration:    3725,
		Description: "A deep dive into database internals.",
	}
	transcript := "Welcome to this talk.\n\nToday we cover B-trees."

	md := formatYouTubeMarkdown(meta, transcript)

	assert.Contains(t, md, "# Database Internals Talk")
	assert.Contains(t, md, "**Channel:** Tech Conference")
	assert.Contains(t, md, "**Published:** 2024-03-15")
	assert.Contains(t, md, "**Duration:** 1:02:05")
	assert.Contains(t, md, "## Description")
	assert.Contains(t, md, "A deep dive into database internals.")
	assert.Contains(t, md, "## Transcript")
	assert.Contains(t, md, "Welcome to this talk.")
}

func TestFormatYouTubeMarkdown_NoTranscript(t *testing.T) {
	meta := &ytdlpMeta{
		Title:       "Music Video",
		Channel:     "Artist",
		UploadDate:  "20240101",
		Duration:    212,
		Description: "Official music video.",
	}

	md := formatYouTubeMarkdown(meta, "")

	assert.Contains(t, md, "# Music Video")
	assert.NotContains(t, md, "## Transcript")
	assert.Contains(t, md, "## Description")
}

func TestFormatDuration(t *testing.T) {
	cases := []struct {
		secs int
		want string
	}{
		{0, "0:00"},
		{65, "1:05"},
		{3600, "1:00:00"},
		{3725, "1:02:05"},
		{90, "1:30"},
	}
	for _, tc := range cases {
		assert.Equal(t, tc.want, formatDuration(tc.secs))
	}
}

func TestYouTubeFetch_FakeBin(t *testing.T) {
	yt := NewYouTube(YouTubeOptions{Bin: fakeTool(t, "yt-dlp"), Timeout: 30 * time.Second})

	result, err := yt.Fetch(t.Context(), "https://www.youtube.com/watch?v=test_id")
	require.NoError(t, err)

	assert.Equal(t, "youtube", yt.Name())
	assert.Equal(t, "video", result.ContentType)
	assert.Equal(t, "Test Video", result.Title)
	assert.Equal(t, "Test Channel", result.Author)
	assert.Equal(t, "https://www.youtube.com/watch?v=test_id", result.FinalURL)
	assert.Contains(t, result.Markdown, "# Test Video")
	assert.Contains(t, result.Markdown, "Hello world this is a test transcript.")
	assert.Equal(t, "yt-dlp", result.Meta["via"])
	assert.Equal(t, "test_id", result.Meta["video_id"])
}

// TestYouTubeFetch_TranscriptSource: the transcript source comes from which
// tracks info.json lists, uploaded captions win over automatic ones, and a
// video without captions is stored as a partial fetch of its description.
func TestYouTubeFetch_TranscriptSource(t *testing.T) {
	cases := []struct {
		subs    string
		source  string
		picked  string
		partial bool
	}{
		{"manual:en,auto:en", "manual", "manual en", false},
		{"auto:en", "auto", "auto en", false},
		{"manual:en,auto:en-orig", "manual", "manual en.", false},
		{"auto:en-orig,auto:en", "auto", "auto en.", false},
		{"none", "none", "", true},
	}
	for _, tc := range cases {
		t.Run(tc.subs, func(t *testing.T) {
			t.Setenv(fakeSubsEnv, tc.subs)
			yt := NewYouTube(YouTubeOptions{Bin: fakeTool(t, "yt-dlp"), Timeout: 30 * time.Second})
			res, err := yt.Fetch(t.Context(), "https://www.youtube.com/watch?v=test_id")
			require.NoError(t, err)

			assert.Equal(t, tc.source, res.Meta["transcript_source"])
			assert.Equal(t, tc.partial, res.Partial)
			assert.Contains(t, res.Markdown, "A test video description.")
			if tc.picked != "" {
				assert.Contains(t, res.Markdown, "This track is "+tc.picked)
			} else {
				assert.NotContains(t, res.Markdown, "## Transcript")
			}
		})
	}
}

func TestYouTubeFetch_PermanentError(t *testing.T) {
	yt := NewYouTube(YouTubeOptions{Bin: fakeTool(t, "yt-dlp-unavailable"), Timeout: 30 * time.Second})
	_, err := yt.Fetch(t.Context(), "https://www.youtube.com/watch?v=gone123")
	require.Error(t, err)

	var pe *PermanentError
	assert.True(t, errors.As(err, &pe), "should be a PermanentError")
	assert.Contains(t, err.Error(), "ERROR: Video unavailable")
	assert.NotContains(t, err.Error(), "WARNING")
}

// TestYouTubeFetch_MaxConcurrent: no more than MaxConcurrent yt-dlp
// processes overlap, and a fetch waiting for a slot honors its context.
func TestYouTubeFetch_MaxConcurrent(t *testing.T) {
	logPath := filepath.Join(t.TempDir(), "runs.log")
	t.Setenv(fakeLogEnv, logPath)
	yt := NewYouTube(YouTubeOptions{Bin: fakeTool(t, "yt-dlp"), Timeout: 30 * time.Second, MaxConcurrent: 2})

	var wg sync.WaitGroup
	for range 6 {
		wg.Go(func() {
			_, err := yt.Fetch(context.Background(), "https://www.youtube.com/watch?v=test_id")
			assert.NoError(t, err)
		})
	}
	require.Eventually(t, func() bool { return len(yt.slots) == cap(yt.slots) }, 10*time.Second, time.Millisecond)
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Millisecond)
	defer cancel()
	_, err := yt.Fetch(ctx, "https://www.youtube.com/watch?v=test_id")
	require.ErrorIs(t, err, context.DeadlineExceeded)
	wg.Wait()

	assert.LessOrEqual(t, maxOverlap(t, logPath), 2)
}

// maxOverlap reads the fake's start/end log and returns the most runs
// that were in progress at once.
func maxOverlap(t *testing.T, path string) int {
	t.Helper()
	data, err := os.ReadFile(path)
	require.NoError(t, err)
	type event struct {
		at    int64
		delta int
	}
	var events []event
	for line := range strings.SplitSeq(strings.TrimSpace(string(data)), "\n") {
		kind, at, ok := strings.Cut(line, " ")
		require.True(t, ok, line)
		nanos, err := strconv.ParseInt(at, 10, 64)
		require.NoError(t, err)
		delta := 1
		if kind == "end" {
			delta = -1
		}
		events = append(events, event{nanos, delta})
	}
	require.Len(t, events, 12)
	slices.SortFunc(events, func(a, b event) int { return cmp.Compare(a.at, b.at) })
	running, peak := 0, 0
	for _, e := range events {
		running += e.delta
		peak = max(peak, running)
	}
	return peak
}

// TestSubprocess_TimeoutKillsProcessGroup: on timeout the whole process
// group dies, helpers holding the output pipes included, and the fetch
// returns promptly with a deadline error instead of waiting for them.
func TestSubprocess_TimeoutKillsProcessGroup(t *testing.T) {
	fetchers := map[string]func(bin string) Fetcher{
		"web2md": func(bin string) Fetcher {
			f, err := NewWeb2MD(Web2MDOptions{Bin: bin, Timeout: 200 * time.Millisecond})
			require.NoError(t, err)
			return f
		},
		"youtube": func(bin string) Fetcher {
			return NewYouTube(YouTubeOptions{Bin: bin, Timeout: 200 * time.Millisecond})
		},
	}
	for name, build := range fetchers {
		t.Run(name, func(t *testing.T) {
			pidFile := filepath.Join(t.TempDir(), "helper.pid")
			t.Setenv(fakePIDFileEnv, pidFile)
			f := build(fakeTool(t, "hang-with-grandchild"))

			start := time.Now()
			_, err := f.Fetch(context.Background(), "https://www.youtube.com/watch?v=test_id")
			assert.Less(t, time.Since(start), 3*time.Second)
			require.ErrorIs(t, err, context.DeadlineExceeded)
			var pe *PermanentError
			assert.False(t, errors.As(err, &pe), "a timeout must stay retryable")

			raw, err := os.ReadFile(pidFile)
			require.NoError(t, err, "the fake never started its helper")
			pid, err := strconv.Atoi(string(raw))
			require.NoError(t, err)
			assert.Eventually(t, func() bool {
				return errors.Is(syscall.Kill(pid, 0), syscall.ESRCH)
			}, 2*time.Second, 10*time.Millisecond, "helper %d outlived the timeout", pid)
		})
	}
}

func TestYouTubeFetch_PlaylistRejected(t *testing.T) {
	yt := NewYouTube(YouTubeOptions{Bin: "yt-dlp"})
	_, err := yt.Fetch(t.Context(), "https://www.youtube.com/playlist?list=PL123")
	require.Error(t, err)

	var pe *PermanentError
	assert.True(t, errors.As(err, &pe), "playlist-only URLs should be permanent errors")
}

func countOccurrences(s, sub string) int {
	count := 0
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			count++
		}
	}
	return count
}

// TestYouTubeFetch_InvalidVideoIDIsPermanent: text in the video-ID position
// that isn't a video ID is never handed to yt-dlp.
func TestYouTubeFetch_InvalidVideoIDIsPermanent(t *testing.T) {
	yt := NewYouTube(YouTubeOptions{Bin: "yt-dlp-must-not-run"})
	_, err := yt.Fetch(t.Context(), "https://www.youtube.com/watch?v=abc%26list%3Dx")
	var pe *PermanentError
	require.ErrorAs(t, err, &pe)
}

// TestFindTranscript_IOErrors: a temp dir or subtitle file that can't be
// read is an error, not a silent "no transcript".
func TestFindTranscript_IOErrors(t *testing.T) {
	_, _, err := findTranscript(filepath.Join(t.TempDir(), "missing"), &ytdlpMeta{})
	require.Error(t, err)

	dir := t.TempDir()
	require.NoError(t, os.Mkdir(filepath.Join(dir, "vid.en.vtt"), 0o700)) // unreadable as a file
	_, _, err = findTranscript(dir, &ytdlpMeta{})
	require.Error(t, err)
}
