package fetcher

import (
	"context"
	"errors"
	"net/url"
	"os"
	"path/filepath"
	"testing"

	"github.com/samsar/curio/internal/urlutil"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestExtractVideoID(t *testing.T) {
	cases := []struct {
		name string
		url  string
		want string
		ok   bool
	}{
		{"standard", "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"no www", "https://youtube.com/watch?v=dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"mobile", "https://m.youtube.com/watch?v=dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"short link", "https://youtu.be/dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"shorts", "https://www.youtube.com/shorts/dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"live", "https://www.youtube.com/live/dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"embed", "https://www.youtube.com/embed/dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"with tracking", "https://www.youtube.com/watch?v=dQw4w9WgXcQ&si=abc&list=PL123", "dQw4w9WgXcQ", true},
		{"playlist only", "https://www.youtube.com/playlist?list=PL123", "", false},
		{"channel page", "https://www.youtube.com/@channel", "", false},
		{"homepage", "https://www.youtube.com/", "", false},
		{"not youtube", "https://example.com/watch?v=dQw4w9WgXcQ", "", false},
		{"youtu.be bare", "https://youtu.be/", "", false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			u, err := url.Parse(tc.url)
			require.NoError(t, err)
			got, ok := urlutil.YouTubeVideoID(u)
			assert.Equal(t, tc.ok, ok)
			if ok {
				assert.Equal(t, tc.want, got)
			}
		})
	}
}

func TestParseVTT_Manual(t *testing.T) {
	vtt := `WEBVTT
Kind: captions
Language: en

00:00:01.000 --> 00:00:04.000
Welcome to this talk about databases.

00:00:04.500 --> 00:00:08.000
Today we'll cover indexing strategies.

00:00:08.500 --> 00:00:12.000
First, let's look at B-trees.

00:00:12.500 --> 00:00:16.000
B-trees are balanced tree structures.

00:00:16.500 --> 00:00:20.000
They provide O(log n) lookups.
`
	got := parseVTT([]byte(vtt))
	assert.Contains(t, got, "Welcome to this talk about databases.")
	assert.Contains(t, got, "B-trees are balanced tree structures.")
	assert.NotContains(t, got, "00:00")
	assert.NotContains(t, got, "WEBVTT")
}

func TestParseVTT_AutoGenerated(t *testing.T) {
	// Auto-generated VTT has <c> tags and rolling duplicate lines.
	vtt := `WEBVTT
Kind: captions
Language: en

00:00:00.000 --> 00:00:02.400 align:start position:0%
welcome<00:00:00.480><c> to</c><c> this</c><c> talk</c>

00:00:02.400 --> 00:00:04.800 align:start position:0%
welcome to this talk
about<00:00:02.880><c> databases</c>

00:00:04.800 --> 00:00:07.200 align:start position:0%
about databases
today<00:00:05.280><c> we</c><c> will</c><c> cover</c>
`
	got := parseVTT([]byte(vtt))
	assert.Contains(t, got, "welcome to this talk")
	assert.Contains(t, got, "about databases")
	assert.Contains(t, got, "today we will cover")
	// Should not contain duplicate "about databases" or HTML tags
	assert.NotContains(t, got, "<c>")
	assert.NotContains(t, got, "<00:00")
	assert.Equal(t, 1, countOccurrences(got, "about databases"))
}

func TestParseVTT_Empty(t *testing.T) {
	assert.Equal(t, "", parseVTT([]byte("WEBVTT\n\n")))
	assert.Equal(t, "", parseVTT([]byte("")))
}

func TestFormatYouTubeMarkdown(t *testing.T) {
	meta := &ytdlpMeta{
		Title:       "Database Internals Talk",
		Channel:     "Tech Conference",
		UploadDate:  "20240315",
		Duration:    3725,
		Description: "A deep dive into database internals.",
	}
	transcript := "Welcome to this talk.\n\nToday we cover B-trees."

	md := formatYouTubeMarkdown(meta, transcript)

	assert.Contains(t, md, "# Database Internals Talk")
	assert.Contains(t, md, "**Channel:** Tech Conference")
	assert.Contains(t, md, "**Published:** 2024-03-15")
	assert.Contains(t, md, "**Duration:** 1:02:05")
	assert.Contains(t, md, "## Description")
	assert.Contains(t, md, "A deep dive into database internals.")
	assert.Contains(t, md, "## Transcript")
	assert.Contains(t, md, "Welcome to this talk.")
}

func TestFormatYouTubeMarkdown_NoTranscript(t *testing.T) {
	meta := &ytdlpMeta{
		Title:       "Music Video",
		Channel:     "Artist",
		UploadDate:  "20240101",
		Duration:    212,
		Description: "Official music video.",
	}

	md := formatYouTubeMarkdown(meta, "")

	assert.Contains(t, md, "# Music Video")
	assert.NotContains(t, md, "## Transcript")
	assert.Contains(t, md, "## Description")
}

func TestFormatDuration(t *testing.T) {
	cases := []struct {
		secs int
		want string
	}{
		{0, "0:00"},
		{65, "1:05"},
		{3600, "1:00:00"},
		{3725, "1:02:05"},
		{90, "1:30"},
	}
	for _, tc := range cases {
		assert.Equal(t, tc.want, formatDuration(tc.secs))
	}
}

func TestYouTubeFetch_FakeBin(t *testing.T) {
	tmpDir := t.TempDir()

	// Write a fake yt-dlp script that outputs JSON and a VTT file.
	fakeBin := filepath.Join(tmpDir, "fake-yt-dlp")
	script := `#!/bin/sh
# Parse the output dir from the -o flag
OUTDIR=""
while [ $# -gt 0 ]; do
    case "$1" in
        -o) OUTDIR="$2"; shift 2;;
        *) shift;;
    esac
done

# Derive the base path (strip the template suffix)
BASEDIR=$(dirname "$OUTDIR")

# Write metadata JSON to info.json file (--write-info-json behavior)
cat > "${BASEDIR}/test_id.info.json" <<'ENDJSON'
{"title":"Test Video","channel":"Test Channel","channel_id":"UC123","upload_date":"20240315","duration":120.0,"description":"A test video description.","tags":["test","video"],"categories":["Education"],"view_count":1000,"like_count":50,"language":"en"}
ENDJSON

# Write a VTT file
cat > "${BASEDIR}/test_id.en.vtt" <<'ENDVTT'
WEBVTT
Kind: captions
Language: en

00:00:01.000 --> 00:00:04.000
Hello world this is a test transcript.

00:00:04.500 --> 00:00:08.000
It has multiple lines of content.
ENDVTT
`
	require.NoError(t, os.WriteFile(fakeBin, []byte(script), 0o755))

	yt := NewYouTube(YouTubeOptions{
		Bin: fakeBin,
	})

	result, err := yt.Fetch(t.Context(), "https://www.youtube.com/watch?v=test_id")
	require.NoError(t, err)

	assert.Equal(t, "youtube", yt.Name())
	assert.Equal(t, "video", result.ContentType)
	assert.Equal(t, "Test Video", result.Title)
	assert.Equal(t, "Test Channel", result.Author)
	assert.Equal(t, "https://www.youtube.com/watch?v=test_id", result.FinalURL)
	assert.Contains(t, result.Markdown, "# Test Video")
	assert.Contains(t, result.Markdown, "Hello world this is a test transcript.")
	assert.Equal(t, "yt-dlp", result.Meta["via"])
	assert.Equal(t, "test_id", result.Meta["video_id"])
}

func TestYouTubeFetch_PermanentError(t *testing.T) {
	tmpDir := t.TempDir()
	fakeBin := filepath.Join(tmpDir, "fake-yt-dlp")
	script := `#!/bin/sh
echo "ERROR: Video unavailable" >&2
exit 1
`
	require.NoError(t, os.WriteFile(fakeBin, []byte(script), 0o755))

	yt := NewYouTube(YouTubeOptions{Bin: fakeBin})
	_, err := yt.Fetch(t.Context(), "https://www.youtube.com/watch?v=gone123")
	require.Error(t, err)

	var pe *PermanentError
	assert.True(t, errors.As(err, &pe), "should be a PermanentError")
}

func TestYouTubeFetch_PlaylistRejected(t *testing.T) {
	yt := NewYouTube(YouTubeOptions{Bin: "yt-dlp"})
	_, err := yt.Fetch(t.Context(), "https://www.youtube.com/playlist?list=PL123")
	require.Error(t, err)

	var pe *PermanentError
	assert.True(t, errors.As(err, &pe), "playlist-only URLs should be permanent errors")
}

func TestPatternDispatcher(t *testing.T) {
	ytFetcher := &stubFetcher{name: "youtube"}
	defaultFetcher := &stubFetcher{name: "native"}

	d := &PatternDispatcher{
		Rules: []Rule{
			{Hosts: YouTubeHosts, Fetcher: ytFetcher},
		},
		Fallback: defaultFetcher,
	}

	cases := []struct {
		url  string
		want string
	}{
		{"https://www.youtube.com/watch?v=abc", "youtube"},
		{"https://youtube.com/watch?v=abc", "youtube"},
		{"https://m.youtube.com/watch?v=abc", "youtube"},
		{"https://youtu.be/abc", "youtube"},
		{"https://example.com/article", "native"},
		{"https://martinfowler.com/articles/feature-toggles.html", "native"},
	}
	for _, tc := range cases {
		f, err := d.For(tc.url)
		require.NoError(t, err)
		assert.Equal(t, tc.want, f.Name(), "url=%s", tc.url)
	}
}

func TestPatternDispatcher_NoFallback(t *testing.T) {
	d := &PatternDispatcher{
		Rules: []Rule{
			{Hosts: []string{"example.com"}, Fetcher: &stubFetcher{name: "test"}},
		},
	}
	_, err := d.For("https://other.com/page")
	assert.ErrorIs(t, err, ErrFetcherNotFound)
}

type stubFetcher struct{ name string }

func (s *stubFetcher) Name() string { return s.name }
func (s *stubFetcher) Fetch(_ context.Context, _ string) (*Result, error) {
	return nil, errors.New("stub")
}

func countOccurrences(s, sub string) int {
	count := 0
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			count++
		}
	}
	return count
}
