package fetcher

import (
	"cmp"
	"context"
	"errors"
	"fmt"
	"io/fs"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/samsar/curio/internal/store"
	"github.com/samsar/curio/internal/urlutil"
)

func TestExtractVideoID(t *testing.T) {
	cases := []struct {
		name string
		url  string
		want string
		ok   bool
	}{
		{"standard", "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"no www", "https://youtube.com/watch?v=dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"mobile", "https://m.youtube.com/watch?v=dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"short link", "https://youtu.be/dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"shorts", "https://www.youtube.com/shorts/dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"live", "https://www.youtube.com/live/dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"embed", "https://www.youtube.com/embed/dQw4w9WgXcQ", "dQw4w9WgXcQ", true},
		{"with tracking", "https://www.youtube.com/watch?v=dQw4w9WgXcQ&si=abc&list=PL123", "dQw4w9WgXcQ", true},
		{"playlist only", "https://www.youtube.com/playlist?list=PL123", "", false},
		{"channel page", "https://www.youtube.com/@channel", "", false},
		{"homepage", "https://www.youtube.com/", "", false},
		{"not youtube", "https://example.com/watch?v=dQw4w9WgXcQ", "", false},
		{"youtu.be bare", "https://youtu.be/", "", false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			u, err := url.Parse(tc.url)
			require.NoError(t, err)
			got, ok := urlutil.YouTubeVideoID(u)
			assert.Equal(t, tc.ok, ok)
			if ok {
				assert.Equal(t, tc.want, got)
			}
		})
	}
}

func TestParseVTT_Manual(t *testing.T) {
	vtt := `WEBVTT
Kind: captions
Language: en

00:00:01.000 --> 00:00:04.000
Welcome to this talk about databases.

00:00:04.500 --> 00:00:08.000
Today we'll cover indexing strategies.

00:00:08.500 --> 00:00:12.000
First, let's look at B-trees.

00:00:12.500 --> 00:00:16.000
B-trees are balanced tree structures.

00:00:16.500 --> 00:00:20.000
They provide O(log n) lookups.
`
	got := parseVTT([]byte(vtt))
	assert.Contains(t, got, "Welcome to this talk about databases.")
	assert.Contains(t, got, "B-trees are balanced tree structures.")
	assert.NotContains(t, got, "00:00")
	assert.NotContains(t, got, "WEBVTT")
}

func TestParseVTT_AutoGenerated(t *testing.T) {
	// Auto-generated VTT has <c> tags and rolling duplicate lines.
	vtt := `WEBVTT
Kind: captions
Language: en

00:00:00.000 --> 00:00:02.400 align:start position:0%
welcome<00:00:00.480><c> to</c><c> this</c><c> talk</c>

00:00:02.400 --> 00:00:04.800 align:start position:0%
welcome to this talk
about<00:00:02.880><c> databases</c>

00:00:04.800 --> 00:00:07.200 align:start position:0%
about databases
today<00:00:05.280><c> we</c><c> will</c><c> cover</c>
`
	got := parseVTT([]byte(vtt))
	assert.Contains(t, got, "welcome to this talk")
	assert.Contains(t, got, "about databases")
	assert.Contains(t, got, "today we will cover")
	// Should not contain duplicate "about databases" or HTML tags
	assert.NotContains(t, got, "<c>")
	assert.NotContains(t, got, "<00:00")
	assert.Equal(t, 1, countOccurrences(got, "about databases"))
}

func TestParseVTT_Empty(t *testing.T) {
	assert.Equal(t, "", parseVTT([]byte("WEBVTT\n\n")))
	assert.Equal(t, "", parseVTT([]byte("")))
}

func TestFormatYouTubeMarkdown(t *testing.T) {
	meta := &ytdlpMeta{
		Title:       "Database Internals Talk",
		Channel:     "Tech Conference",
		UploadDate:  "20240315",
		Duration:    3725,
		Description: "A deep dive into database internals.",
	}
	transcript := "Welcome to this talk.\n\nToday we cover B-trees."

	md := formatYouTubeMarkdown(meta, transcript)

	assert.Contains(t, md, "# Database Internals Talk")
	assert.Contains(t, md, "**Channel:** Tech Conference")
	assert.Contains(t, md, "**Published:** 2024-03-15")
	assert.Contains(t, md, "**Duration:** 1:02:05")
	assert.Contains(t, md, "## Description")
	assert.Contains(t, md, "A deep dive into database internals.")
	assert.Contains(t, md, "## Transcript")
	assert.Contains(t, md, "Welcome to this talk.")
}

func TestFormatYouTubeMarkdown_NoTranscript(t *testing.T) {
	meta := &ytdlpMeta{
		Title:       "Music Video",
		Channel:     "Artist",
		UploadDate:  "20240101",
		Duration:    212,
		Description: "Official music video.",
	}

	md := formatYouTubeMarkdown(meta, "")

	assert.Contains(t, md, "# Music Video")
	assert.NotContains(t, md, "## Transcript")
	assert.Contains(t, md, "## Description")
}

func TestFormatDuration(t *testing.T) {
	cases := []struct {
		secs int
		want string
	}{
		{0, "0:00"},
		{65, "1:05"},
		{3600, "1:00:00"},
		{3725, "1:02:05"},
		{90, "1:30"},
	}
	for _, tc := range cases {
		assert.Equal(t, tc.want, formatDuration(tc.secs))
	}
}

func TestYouTubeFetch_FakeBin(t *testing.T) {
	yt := NewYouTube(YouTubeOptions{Bin: fakeTool(t, "yt-dlp"), Timeout: 30 * time.Second})

	result, err := yt.Fetch(t.Context(), "https://www.youtube.com/watch?v=test_id")
	require.NoError(t, err)

	assert.Equal(t, "youtube", yt.Name())
	assert.Equal(t, store.ContentTypeVideo, result.ContentType)
	assert.Equal(t, "Test Video", result.Title)
	assert.Equal(t, "Test Channel", result.Author)
	assert.Equal(t, "https://www.youtube.com/watch?v=test_id", result.FinalURL)
	assert.Contains(t, result.Markdown, "# Test Video")
	assert.Contains(t, result.Markdown, "Hello world this is a test transcript.")
	assert.Equal(t, "yt-dlp", result.Meta["via"])
	assert.Equal(t, "test_id", result.Meta["video_id"])
}

// TestYouTubeFetch_TranscriptSource: the transcript source comes from which
// tracks info.json lists, uploaded captions win over automatic ones, and a
// video without captions is stored as a partial fetch of its description.
func TestYouTubeFetch_TranscriptSource(t *testing.T) {
	cases := []struct {
		subs    string
		source  string
		picked  string
		partial bool
	}{
		{"manual:en,auto:en", "manual", "manual en", false},
		{"auto:en", "auto", "auto en", false},
		{"manual:en,auto:en-orig", "manual", "manual en.", false},
		{"auto:en-orig,auto:en", "auto", "auto en.", false},
		{"none", "none", "", true},
	}
	for _, tc := range cases {
		t.Run(tc.subs, func(t *testing.T) {
			t.Setenv(fakeSubsEnv, tc.subs)
			yt := NewYouTube(YouTubeOptions{Bin: fakeTool(t, "yt-dlp"), Timeout: 30 * time.Second})
			res, err := yt.Fetch(t.Context(), "https://www.youtube.com/watch?v=test_id")
			require.NoError(t, err)

			assert.Equal(t, tc.source, res.Meta["transcript_source"])
			assert.Equal(t, tc.partial, res.Partial)
			assert.Contains(t, res.Markdown, "A test video description.")
			if tc.picked != "" {
				assert.Contains(t, res.Markdown, "This track is "+tc.picked)
				assert.Empty(t, res.PartialReason)
			} else {
				assert.NotContains(t, res.Markdown, "## Transcript")
				assert.Equal(t, `no usable captions for sub_langs "`+DefaultYouTubeSubLangs+`"`, res.PartialReason)
			}
		})
	}
}

// TestYouTubeFetch_RunFailures: a video yt-dlp reports gone fails
// permanently; any other failed run, and a run that wrote no info.json,
// is retried. Only ERROR lines are quoted.
func TestYouTubeFetch_RunFailures(t *testing.T) {
	cases := []struct {
		mode      string
		permanent bool
		quoted    string
	}{
		{"yt-dlp-unavailable", true, "ERROR: Video unavailable"},
		{"yt-dlp-error", false, "ERROR: [youtube] test_id: Unable to extract initial player response"},
		{"yt-dlp-no-info", false, "yt-dlp produced no info.json"},
	}
	for _, tc := range cases {
		t.Run(tc.mode, func(t *testing.T) {
			yt := NewYouTube(YouTubeOptions{Bin: fakeTool(t, tc.mode), Timeout: 30 * time.Second})
			_, err := yt.Fetch(t.Context(), "https://www.youtube.com/watch?v=test_id")
			require.Error(t, err)

			var pe *PermanentError
			assert.Equal(t, tc.permanent, errors.As(err, &pe), "permanent: %v", err)
			assert.Contains(t, err.Error(), tc.quoted)
			assert.NotContains(t, err.Error(), "WARNING")
		})
	}
}

// TestFakeYTDLP_FailedCaption: the fake fails a caption download the way
// yt-dlp does. By default the video is aborted before its info.json is
// written; with --ignore-errors the failure is a warning and the rest is
// written.
func TestFakeYTDLP_FailedCaption(t *testing.T) {
	const failure = "Unable to download video subtitles for 'en': HTTP Error 429: Too Many Requests"
	bin := fakeTool(t, "yt-dlp")
	t.Setenv(fakeSubsEnv, "auto:en!429")
	for _, ignoreErrors := range []bool{false, true} {
		t.Run(fmt.Sprintf("ignore-errors=%v", ignoreErrors), func(t *testing.T) {
			dir := t.TempDir()
			args := []string{"--write-info-json", "-o", filepath.Join(dir, "%(id)s"), "https://www.youtube.com/watch?v=test_id"}
			if ignoreErrors {
				args = append([]string{"--ignore-errors"}, args...)
			}
			stderr, err := runCapped(t.Context(), 30*time.Second, nil, bin, args...)
			_, statErr := os.Stat(filepath.Join(dir, "test_id.info.json"))
			if ignoreErrors {
				require.NoError(t, err)
				assert.Contains(t, stderr, "WARNING: "+failure)
				assert.NoError(t, statErr)
				return
			}
			var exitErr *exec.ExitError
			require.ErrorAs(t, err, &exitErr)
			assert.Equal(t, 1, exitErr.ExitCode())
			assert.Contains(t, stderr, "ERROR: "+failure)
			assert.ErrorIs(t, statErr, fs.ErrNotExist)
		})
	}
}

// TestYouTubeFetch_FailedCaptionDownload: yt-dlp runs with --ignore-errors,
// so a caption track that fails to download no longer costs the video.
// When it was the only track, the video is stored as a partial of its
// description that says why; when another track downloaded, that one is
// the transcript.
func TestYouTubeFetch_FailedCaptionDownload(t *testing.T) {
	const failure = "Unable to download video subtitles for 'en': HTTP Error 429: Too Many Requests"
	cases := []struct {
		subs    string
		partial bool
		reason  string
	}{
		{"auto:en!429", true, "transcript not downloaded: yt-dlp: " + failure},
		{"auto:en!429,manual:en-GB", false, ""},
	}
	for _, tc := range cases {
		t.Run(tc.subs, func(t *testing.T) {
			argsPath := filepath.Join(t.TempDir(), "args")
			t.Setenv(fakeArgsEnv, argsPath)
			t.Setenv(fakeSubsEnv, tc.subs)
			yt := NewYouTube(YouTubeOptions{Bin: fakeTool(t, "yt-dlp"), Timeout: 30 * time.Second})
			res, err := yt.Fetch(t.Context(), "https://www.youtube.com/watch?v=test_id")
			require.NoError(t, err)

			runs := ytdlpRuns(t, argsPath)
			require.Len(t, runs, 1)
			assert.Contains(t, runs[0], "--ignore-errors")
			assert.Equal(t, store.ContentTypeVideo, res.ContentType)
			assert.Equal(t, "Test Video", res.Title)
			assert.Contains(t, res.Markdown, "A test video description.")
			assert.Equal(t, tc.partial, res.Partial)
			assert.Equal(t, tc.reason, res.PartialReason)
			if tc.partial {
				assert.NotContains(t, res.Markdown, "## Transcript")
				assert.Equal(t, transcriptNone, res.Meta["transcript_source"])
			} else {
				assert.Contains(t, res.Markdown, "This track is manual en-GB.")
			}
		})
	}
}

// TestYouTubeFetch_PartialReasonIsCapped: however many caption downloads
// fail, the reason quotes no more of them than any error text does.
func TestYouTubeFetch_PartialReasonIsCapped(t *testing.T) {
	tracks := make([]string, 40)
	for i := range tracks {
		tracks[i] = fmt.Sprintf("auto:en-l%02d!429", i)
	}
	t.Setenv(fakeSubsEnv, strings.Join(tracks, ","))
	yt := NewYouTube(YouTubeOptions{Bin: fakeTool(t, "yt-dlp"), Timeout: 30 * time.Second})
	res, err := yt.Fetch(t.Context(), "https://www.youtube.com/watch?v=test_id")
	require.NoError(t, err)
	require.True(t, res.Partial)
	assert.LessOrEqual(t, len(res.PartialReason), maxErrorBody+len("…"))
	assert.True(t, strings.HasPrefix(res.PartialReason, "transcript not downloaded: yt-dlp: Unable to download video subtitles for 'en-l00'"))
	assert.True(t, strings.HasSuffix(res.PartialReason, "…"))
}

// TestYouTubeFetch_MaxConcurrent: no more than MaxConcurrent yt-dlp
// processes overlap, and a fetch waiting for a slot honors its context.
func TestYouTubeFetch_MaxConcurrent(t *testing.T) {
	logPath := filepath.Join(t.TempDir(), "runs.log")
	t.Setenv(fakeLogEnv, logPath)
	yt := NewYouTube(YouTubeOptions{Bin: fakeTool(t, "yt-dlp"), Timeout: 30 * time.Second, MaxConcurrent: 2})

	var wg sync.WaitGroup
	for range 6 {
		wg.Go(func() {
			_, err := yt.Fetch(context.Background(), "https://www.youtube.com/watch?v=test_id")
			assert.NoError(t, err)
		})
	}
	require.Eventually(t, func() bool { return len(yt.slots) == cap(yt.slots) }, 10*time.Second, time.Millisecond)
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Millisecond)
	defer cancel()
	_, err := yt.Fetch(ctx, "https://www.youtube.com/watch?v=test_id")
	require.ErrorIs(t, err, context.DeadlineExceeded)
	wg.Wait()

	assert.LessOrEqual(t, maxOverlap(t, logPath), 2)
}

// maxOverlap reads the fake's start/end log and returns the most runs
// that were in progress at once.
func maxOverlap(t *testing.T, path string) int {
	t.Helper()
	data, err := os.ReadFile(path)
	require.NoError(t, err)
	type event struct {
		at    int64
		delta int
	}
	var events []event
	for line := range strings.SplitSeq(strings.TrimSpace(string(data)), "\n") {
		kind, at, ok := strings.Cut(line, " ")
		require.True(t, ok, line)
		nanos, err := strconv.ParseInt(at, 10, 64)
		require.NoError(t, err)
		delta := 1
		if kind == "end" {
			delta = -1
		}
		events = append(events, event{nanos, delta})
	}
	require.Len(t, events, 12)
	slices.SortFunc(events, func(a, b event) int { return cmp.Compare(a.at, b.at) })
	running, peak := 0, 0
	for _, e := range events {
		running += e.delta
		peak = max(peak, running)
	}
	return peak
}

func TestYouTubeFetch_PlaylistRejected(t *testing.T) {
	yt := NewYouTube(YouTubeOptions{Bin: "yt-dlp"})
	_, err := yt.Fetch(t.Context(), "https://www.youtube.com/playlist?list=PL123")
	require.Error(t, err)

	var pe *PermanentError
	assert.True(t, errors.As(err, &pe), "playlist-only URLs should be permanent errors")
}

func countOccurrences(s, sub string) int {
	count := 0
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			count++
		}
	}
	return count
}

// TestYouTubeFetch_InvalidVideoIDIsPermanent: text in the video-ID position
// that isn't a video ID is never handed to yt-dlp.
func TestYouTubeFetch_InvalidVideoIDIsPermanent(t *testing.T) {
	yt := NewYouTube(YouTubeOptions{Bin: "yt-dlp-must-not-run"})
	_, err := yt.Fetch(t.Context(), "https://www.youtube.com/watch?v=abc%26list%3Dx")
	var pe *PermanentError
	require.ErrorAs(t, err, &pe)
}

// TestFindTranscript_IOErrors: a temp dir or subtitle file that can't be
// read is an error, not a silent "no transcript".
func TestFindTranscript_IOErrors(t *testing.T) {
	_, _, err := findTranscript(filepath.Join(t.TempDir(), "missing"), &ytdlpMeta{})
	require.Error(t, err)

	dir := t.TempDir()
	require.NoError(t, os.Mkdir(filepath.Join(dir, "vid.en.vtt"), 0o700)) // unreadable as a file
	_, _, err = findTranscript(dir, &ytdlpMeta{})
	require.Error(t, err)
}

// TestYouTubeFetch_SubLangs: yt-dlp gets DefaultYouTubeSubLangs when
// sub_langs isn't configured, and a configured value as is.
func TestYouTubeFetch_SubLangs(t *testing.T) {
	cases := []struct{ configured, want string }{
		{"", "en,en-(?-i:[A-Z]{2})"},
		{"de.*,en", "de.*,en"},
	}
	for _, tc := range cases {
		t.Run("configured="+tc.configured, func(t *testing.T) {
			argsPath := filepath.Join(t.TempDir(), "args")
			t.Setenv(fakeArgsEnv, argsPath)
			yt := NewYouTube(YouTubeOptions{Bin: fakeTool(t, "yt-dlp"), Timeout: 30 * time.Second, SubLangs: tc.configured})
			_, err := yt.Fetch(t.Context(), "https://www.youtube.com/watch?v=test_id")
			require.NoError(t, err)

			runs := ytdlpRuns(t, argsPath)
			require.Len(t, runs, 1)
			args := runs[0]
			i := slices.Index(args, "--sub-langs")
			require.True(t, i >= 0 && i+1 < len(args), "no --sub-langs value in %q", args)
			assert.Equal(t, tc.want, args[i+1])
			assert.NotContains(t, args[i+2:], "--sub-langs")
		})
	}
}

// TestDefaultYouTubeSubLangs_Picks: what the default has yt-dlp download
// from caption layouts YouTube serves. Tracks are listed as yt-dlp sees
// them: uploaded ones first, then automatic ones without an uploaded
// track of the same key. YouTube adds an automatic en-<source> track, a
// machine translation into English, for every uploaded caption language,
// and en-orig, a copy of the automatic en.
func TestDefaultYouTubeSubLangs_Picks(t *testing.T) {
	cases := []struct {
		name   string
		tracks []string
		want   []string
	}{
		{
			"uploaded en-GB, zh and ja",
			[]string{"en-GB", "zh", "ja", "en-orig", "en", "fr", "de", "en-en-GB", "en-zh", "en-ja"},
			[]string{"en", "en-GB"},
		},
		{"uploaded en", []string{"en", "en-orig", "en-en"}, []string{"en"}},
		{"automatic only, a Spanish video", []string{"es-orig", "es", "en"}, []string{"en"}},
		{
			"uploaded en-US and a named English track",
			[]string{"en-US", "en-nP7-2PuUl7o", "en-orig", "en", "en-en-US", "en-zh-Hans", "en-pt-BR"},
			[]string{"en", "en-US"},
		},
		{"stream replay with only its live chat", []string{"live_chat"}, nil},
		{"uploaded Catalan", []string{"ca", "en-orig", "en", "en-ca"}, []string{"en"}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			assert.Equal(t, tc.want, ytdlpPicksSubs(DefaultYouTubeSubLangs, tc.tracks))
		})
	}
}

// ytdlpPicksSubs mirrors how yt-dlp turns --sub-langs into the caption
// tracks it downloads (YoutubeDL.process_subtitles and
// orderedSet_from_options): each comma-separated item is full-matched, as
// a case-insensitive regular expression, against every track key in turn,
// and an item with a leading '-' removes its matches instead. Each track
// is picked once, in the order first picked.
func ytdlpPicksSubs(subLangs string, tracks []string) []string {
	var picked []string
	for item := range strings.SplitSeq(subLangs, ",") {
		pattern, discard := strings.CutPrefix(item, "-")
		re := regexp.MustCompile(`(?i)^(?:` + pattern + `)$`)
		for _, track := range tracks {
			switch {
			case !re.MatchString(track):
			case discard:
				picked = slices.DeleteFunc(picked, func(p string) bool { return p == track })
			case !slices.Contains(picked, track):
				picked = append(picked, track)
			}
		}
	}
	return picked
}
